require('plugins.packer')
require('config.mappings')
require('config.settings')
require('commands.comment')
require('commands.folding')
require('plugins.nord')
require('plugins.treesitter')
require('plugins.lsp')
